# docker build . --tag juancho85/nginx_webserver:20190217
# See php extensions https://github.com/webdevops/Dockerfile/blob/master/docker/php/ubuntu-18.04/Dockerfile
FROM webdevops/php-nginx:ubuntu-18.04

#####################################
# XDEBUG
#####################################
RUN apt-install php-xdebug