version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongolti
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lti
    ports:
      - 8081:8081
    volumes:
      - ./mongodata:/data/db